# serverless.yml

service: apollo-sls
provider:
  name: aws
  runtime: nodejs14.x
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
